// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace SkylinesMaps
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "SkylinesMaps";
        public const string Version     = "1.1.0";
        public const string Title       = "Skylines Maps";
        public const string Description = "A live traffic infoview that resembles real life navigation apps and a journey length mode";
    }
}
